# Generated by Django 2.2.5 on 2021-07-08 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='cost_price',
        ),
        migrations.RemoveField(
            model_name='sku',
            name='market_price',
        ),
    ]
