# Generated by Django 2.2.5 on 2021-07-08 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20210708_0336'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sku',
            name='caption',
        ),
    ]
