# Generated by Django 2.2.5 on 2021-07-08 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0004_auto_20210708_0713'),
    ]

    operations = [
        migrations.AddField(
            model_name='sku',
            name='caption',
            field=models.CharField(default='', max_length=100, verbose_name='副标题'),
        ),
    ]
